# Inserts a blank line between shell prompts
add_newline = true
# format = """$directory$git_branch$git_status$character"""
format = """
[â”Œ](gray dimmed) $directory$git_branch$git_status$fill$all
[â””](gray dimmed) $character """

[fill]
symbol = "â”€"
style = "dimmed gray"
# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[line_break]
disabled = true
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
[aws.region_aliases]
us-gov-west-1 = "gw"
us-east-1 = "va"

[docker_context]
format = "[ğŸ‹ $context](blue bold)"

[git_branch]
format = "[$symbol$branch]($style) "
[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style = "yellow"
up_to_date = "[âœ“](green)"

[kubernetes]
format = '[${symbol}$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.localcluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[lua]
format = "[${symbol}$version](bold blue) "

[nodejs]
format = "[${symbol}$version](bold green) "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[shell]
disabled = false
